### ISSUE TITLE
IBS specs & issue tracking

### ISSUE THREAD

**Issue by cocoyoon** [InfraBlockchain/infra-relay#10]
# InfraBlockspace

## ToDo
- [x] Refactoring crate name
- [ ] Genesis build
- [ ] Pallet configure details
- [ ] XCM
- [ ] System Token Implement
- [ ] PoT Integration
- [ ] Consensus support
- [ ] Governance support

### Tracking
- [ ] PoT
    - [ ] Extend tx metadata
    - [ ] Extend tx format to support `fee payer`
    - [ ] Vote Aggregation
    - [ ] Session Pallet
- [ ] System Token
    - [x] `pallet-infra-asset-tx-payment` Integration
    - [ ] Common parameters
    - [ ] Apply exchange rate
