### ISSUE TITLE
InfraBlockspace Development Tracking

### ISSUE THREAD

**Issue by cocoyoon** [InfraBlockchain/infra-relay#15]
## ToDo
- [x] Extends tx format to support `fee payer`(https://github.com/InfraBlockchain/infra-substrate/pull/48)
- [x] Signed Extension for pot (https://github.com/InfraBlockchain/infra-substrate/pull/21)
- [x] Collect vote on `validate_block` blob(https://github.com/InfraBlockchain/infra-cumulus/pull/39)
- [x] Aggregate vote for each parachain block (https://github.com/InfraBlockchain/infra-relay-chain/pull/18)
- [x] Sesson Pallet
- [x] System Token Weight
- [x] Fee Table
- [x] Validator Reward Management

## Proof of Transaction

트랜잭션을 많이 일으키는 서비스 제공자 혹은 parachain 을 운영하는 어떠한 계정이 어떠한 네트워크의 블록 생성자, 즉 validator를 선출해내는 컨센서스이다. 트랜잭션 안에 투표를 첨가하여 특정 시점에 수집된 투표에 대한 집계를 통해 validator 를 선별해내며 이를 ***Transaction-as-a-Vote*** 라 한다.

### Transaction As a Vote

인프라 블록스페이스의 *validator* 는 **Transaction-as-a-Vote** 에 의해 선출된다. 트랜잭션 안에 투표를 하게 되고 특정 시점에 해당 투표를 기반으로 validator가 선정이 된다.

- 트랜잭션마다 validator 에 대한 투표 정보를 포함시킨다
- **블록체인 트랜잭션을 많이 일으키는 서비스의 계정이** 블록 생성자로 선출되고 **법정화폐 기반 트랜잭션 수수료**를 보상으로 받는다

**Overview**

![https://i.imgur.com/9EylC2B.png](https://i.imgur.com/9EylC2B.png)

인프라 블록스페이스의 컨센서스는 Proof-of-Transaction(PoT) 기반으로 이루어진다. 패러체인 블록안에 포함된 트랜잭션 안에 특정 validator 에 대한 투표 정보를 포함시켜 인프라 블록체인(패러체인)의 Proof-of-Validity(PoV) 에 포함되어 릴레이 체인으로 전달된다.릴레이 체인에서는 해당 PoV 를 검증하고 (1) 트랜잭션 안에 포함된 투표 정보를 수집한 후 (2) 각 패러체인들로부터 들어온 투표 정보들을 자신의 상태에 반영한다. 릴레이 체인의 특정 시점이 지나면 집계한 투표를 기반으로 validator set 을 변경하게 된다.

### Implementation

- **Parachain**
    
    인프라 블록스페이스에서 Relay Chain 과 연결되어 shared security 를 형성하여 특정 서비스(App Chain)를 수행하는 블록체인 네트워크이다.
    
    `Parachain System`
    
    Cumulus 기반의 parachain 의 기본적인 시스템 pallet 로써 다음과 같은 역할을 수행한다.
    
    - **Validation data의 수집**
    - DMP, UMP message
    - Relay Chain 과 Runtime Upgrade 조율
    - **자신의 블록을 검증할 수 있는 wasm 함수 정의**
    
    `Transaction Format`
    
    Transaction-as-a-Vote 를 수행하기 위해 parachain 으로 들어오는 트랜잭션 메타데이터를 확장함으로써 트랜잭션안에 투표 정보를  넣을 수 있게 된다. 기본적인 트랜잭션 구조에서 인프라 블록스페이스의 parachain 은 투표 정보까지 인코딩되어 Runtime 으로 들어오게된다
    
    ```rust
    type SignedPayload = (Address, Signature, Extra);
    ```
    
    Extra 에는 트랜잭션에 추가하고 싶은 메타 데이터가 있다. 예를 들면, `Nonce` 나 `SpecVersion` 같이 기본 트랜잭션 포맷에 데이터를 추가할 수 있으며 이를 기반으로 트랜잭션 유효성 검증을 진행할 수 있다. **인프라 블록체인에서는 Native Token 없이 거버넌스에 의해 승인된 토큰이 트랜잭션 수수료로 사용되며 해당 기능을 가능하게 하는 Extra 타입을 정의해준다**
    
    [Pallet: Asset Transaction Payment ](https://www.notion.so/Pallet-Asset-Transaction-Payment-7a6d151ad34847cc85b2620b0856388c)
    
    ```rust
    pub type SignedExtra = (
        ...
    		pallet_asset_tx_payment::ChargeAssetTxPayment<Runtime>,
    );
    ```
    
    `PoV`
    
    Collator 는 PoV(Proof-of-Validity)형태로 Relay Chain 에 전달하게 된다.  해당 데이터에는 Relay Chain Validator 가 parachain 의 상태를 다 알지 못하더라도 유효성 검증을 할 수 있게 트랜잭션에 변경된 state 에 한 storage proof 가 포함되어 있다. 
    
    PoV 는 `ParachainBlockData` 타입이 Parity SCALE Codec 으로 인코딩된 형태이다. 
    
    ```rust
    pub struct ParachainBlockData = {
    	pub header,
    	pub extrinsics,
    	pub storage_proof
    };
    pub struct Pov: Vec<u8> = BlockData(ParachainBlockdata.encode());
    ```
    

- RelayChain
    
    Relay Chain Validator 가 parachain 블록을 검증하는 역할을 수행하고 해당 블록이 유효하다면 자신의 블록안에 포함시키는 역할을 수행한다. 투표 정보는 parachain 블록안에 담겨있고 Validator 는 해당 블록을 검증할 때, 투표 정보를 가져온다. 현재 Validator 가 parachain 블록을 검증하는 로직은 다음과 같다.
    
    1. Parachain 이 Relay Chain 에 들어올 때 자신의 블록을 검증할 수 있는 부분과 State Transition 부분이 담긴 WASM 을 Relay Chain storage에 저장한다. 
        
        ```rust
        /// Parachain validation code.
        pub struct ValidationCode(pub Vec<u8>);
        ```
        
    2. Relay Chain Validator 는 parachain block 을 검증하 때 해당 WASM 을 기반으로 유효성을 검증한다. 
        
        ```rust
        // parachain_system
        fn validate_block(pov: Vec<u8>) {
        	let (header, extrinsics, storage_proof) = ParachainBlock::decode(pov).deconstruct();
        	let block = Block::new(header, extrinsics);
        	// CREATE STORAGE LAYER
        	run_with_externalities(|backend| {
        		Executives::execute_block(block);
        		// Get data for collation
        		let vote_info: Vec<(who, asset_id, weight))> = crate::VoteInfo<Runtime>::get();
        		// Return validation result
        		ValidationResult {
        			..
        			vote_info
        		}
        	})
        }
        ```
        
    3. Validator 는 parachain 블록의 검증결과를 반환하게 되고 Collator 쪽에서 보낸 Collation 과 대조를 통해 블록 검증을 진행한다.
        
        ```rust
        let res: ValidationResult = validate_block(pov);
        IF HASH(COMMITMENT_BY_COLLATION) == HASH(COMMITMENT_BY_VALIDATION):
        	DO SOMETHING WITH `res.vote_info`
        ELSE:
        	INVALID BLOCK
        ```
        
### Others

- 트랜잭션 포맷 예시
    
    ```rust
    // Basic transfer
    
    // Pallet Info
    let pallet_index: u8 = 5; 
    let call_index: u8 = 0;
    
    // Call Params
    let from = AccountKeyring::Alice.to_account_id();
    let to = MultiAddress::Id::<_, u32>(AccountKeyring::Bob.to_account_id());
    let amount = Compact::from(123456789012345u128);
    
    // Pay Master
    let pay_master = AccountKeyring::PayMaster.to_account_id()
    
    // Nonce
    let alice_nonce = get_nonce(&from).await;
    
    // Call
    let call = (pallet_index, call_index, dest, amount);
    
    // Vote Struct
    #[derive(Encode, Decode)]
    pub struct Vote<AccountId> {
        candidate: Option<AccountId>
    }
    
    // Fee
    pub struct Fee<AccountId, Balance> {
    	pay_master: Option<AccountId> // fee 를 대신 내주는 account
    	asset_id: u32,
    	tip: Balance,
    }
    
    // Extra 메타데이터
    let extra = (
        Era::Immortal, 
        Compact(alice_nonce), // nonce
        Compact(500000000000000u128), // tip
    		Fee::new(
    				Some(pay_master.clone()), // fee 대납. None 일시 client 가 지불
    				1, // asset id
    				0 // tip
    		),
        Vote::new(
    				Some(from.clone()) // 투표대상
    		), 
    );
    
    // 런타임 version
    let runtime_version = get_runtime_version().await;
    // Genesis 해시
    let genesis_hash = get_genesis_hash().await;
    
    let additional = (
        runtime_version.spec_version,
        runtime_version.transaction_version,
        genesis_hash,
        genesis_hash,
    );
    
    // Signature payload
    let signature = {
        let full_unsigned_payload = (&call, &extra, &additional);
        let full_unsigned_payload_scale_bytes = full_unsigned_payload.encode();
        if full_unsigned_payload_scale_bytes.len() > 256 {
            AccountKeyring::Alice.sign(&blake2_256(&full_unsigned_payload_scale_bytes[..]))
        } else {
            AccountKeyring::Alice.sign(&full_unsigned_payload_scale_bytes)
        }
    };
    
    // Unchecked Extrinsic 의 signature payload
    let sig_to_encode = Some((
        MultiAddress::Id::<_, u32>(from.clone()),
        MultiSignature::Sr25519(signature),
        extra
    ));
    
    // Extrinsic 인코딩 및 hex 형태로 변환
    let payload_scale_encode = encode_extrinsic(sig_to_encode, call);
    let payload_hex = format!("0x{}", hex::encode(payload_scale_encode));
    
    // RPC 를 통해 Extrinsic 제출
    match rpc_to_localhost("author_submitExtrinsic", [payload_hex]).await {
        Ok(r) => println!("Value is {:?}", r),
        Err(e) => println!("Error! {:?}", e),
    }
    ```
